POST http://localhost:4000/createCoin
Content-Type: application/json

{
    "name": "WizardNaut",
    "ticker": "WizardNaut",
    "rank": "Quantum Admiral",
    "rankDesc": "Respected leaders who command Naut crews across uncharted star systems, making first contact, charting unknown constellations, and safeguarding the Solana territories.",
    "desc": "Wielder of the Sword of Code, a relic forged in the tectonic vaults of SOL-320B. KnightNaut is loyal to the original Naut Order — protector of the weak and hunter of the corrupted. His path is perilous, for many believe he may one day face a terrible truth: a former comrade turned Void-bound traitor."
}
###

GET http://localhost:4000/getLastCreatedCoin


###

POST http://localhost:4000/updateCoin/WizardNaut/1234