POST http://localhost:4000/createCoin
Content-Type: application/json

{
    "name": "PepeNaut",
    "ticker": "PepeNaut",
    "rank": "Cosmic Legend",
    "rankDesc": "The stuff of interstellar legend—peerless Nauts whose exploits transcend the known universe, heroes whose daring adventures inspire generations and whose names become timeless myths.",
    "desc": "Meme incarnate. Sentient irony. Born from the laughter fields of SOL-320B, PepeNaut exists in a state of sublime awareness — a balance of joy and melancholy, past and present. He leads not through command, but through resonance. Crews follow him without question, drawn by a force even the crypto-elders struggle to define. In moments of crisis, when tension cracks and the stars seem to sigh, he simply shrugs and says, \"Feels like fate, man.\" None can tell if he's joking… or prophesying."
}
###

GET http://localhost:4000/getLastCreatedCoin


###

POST http://localhost:4000/updateCoin/PepeNaut/demoAddress