POST http://localhost:4000/createCoin
Content-Type: application/json

{
    "name": "DarkNaut",
    "ticker": "DarkNaut",
    "rank": "Nebula Commander",
    "rankDesc": "Elite Nauts renowned for leading complex missions into mysterious nebulae and confronting unknown cosmic phenomena—unlocking secrets that alter the fate of galaxies.",
    "desc": "He doesn’t need superpowers. He is the power. Operating from the shadowy void decks of Station Xeon, DarkNaut is a myth wrapped in quantum armor — the lone protector who answers no call but justice. His mind is a weapon. His fists, silent verdicts. His ship? Never seen, only felt… in fear. When questioned, his voice echoes through the darkest corners of the fleet: “It’s not who I am underneath, but what I do that defines me.” They call him paranoid. They call him obsessed. But when rogue Nauts vanish and Void agents fall without a trace… they also call him the last line."
}
###

GET http://localhost:4000/getLastCreatedCoin


###

POST http://localhost:4000/updateCoin/WizardNaut/1234

###

GET http://localhost:4000/validateCoin/Shiloh